// lib/Screens/AddAuthAccounts/ManualSecretEntryPage.dart

import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:zenauth/Controllers/HomeController.dart';
import 'package:zenauth/Models/AuthenticatorAccountModel.dart'; // Needed for model instantiation

class ManualSecretEntryPage extends StatelessWidget {
  // Access the existing HomeController instance
  final HomeController controller = Get.find<HomeController>();

  // Text Controllers for manual inputs
  final TextEditingController _issuerController = TextEditingController();
  final TextEditingController _usernameController = TextEditingController();
  final TextEditingController _secretController = TextEditingController();

  // Global key to validate the form
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();

  ManualSecretEntryPage({super.key});

  // --- Form Submission Logic ---
  void _submitAccount() {
    if (_formKey.currentState!.validate()) {
      final String issuer = _issuerController.text.trim();
      final String username = _usernameController.text.trim();
      // Sanitize secret: remove spaces and convert to uppercase for Base32 standard
      final String secret = _secretController.text
          .trim()
          .replaceAll(' ', '')
          .toUpperCase();

      // 1. Create the new account object (minimal state)
      final newAccount = AuthenticatorAccount(
        // Use an empty ID; the controller will generate the final UUID
        id: '',
        issuer: issuer.isNotEmpty ? issuer : 'Unnamed Service',
        username: username.isNotEmpty ? username : 'User',
        secret: secret,
        digits: 6, // Default to 6 digits (most common)
        period: 30, // Default to 30 seconds (most common)
        color: null, // Color will be generated by the controller
      );

      // 2. Add the account via the controller
      controller.addAccount(newAccount);

      // 3. Navigate back
      Get.back();
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Add Account Manually'),
        actions: [
          IconButton(icon: const Icon(Icons.done), onPressed: _submitAccount),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              // --- Secret Key Field (Required) ---
              TextFormField(
                controller: _secretController,
                decoration: const InputDecoration(
                  labelText: 'Secret Key (Base32)',
                  hintText: 'e.g., JBSWY3DPEHPK3PXP',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.vpn_key),
                ),
                keyboardType: TextInputType.text,
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Secret key cannot be empty.';
                  }
                  // Base32 secrets should be reasonably long
                  if (value.trim().replaceAll(' ', '').length < 8) {
                    return 'Secret key is too short.';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 24),

              // --- Issuer Field ---
              TextFormField(
                controller: _issuerController,
                decoration: const InputDecoration(
                  labelText: 'Service Name (Issuer)',
                  hintText: 'e.g., Google, Facebook',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.business),
                ),
                keyboardType: TextInputType.text,
              ),
              const SizedBox(height: 16),

              // --- Username/Account Field ---
              TextFormField(
                controller: _usernameController,
                decoration: const InputDecoration(
                  labelText: 'Account Name (Username/Email)',
                  hintText: 'e.g., user@example.com',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.person),
                ),
                keyboardType: TextInputType.emailAddress,
              ),
              const SizedBox(height: 32),
            ],
          ),
        ),
      ),
    );
  }
}
